//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectVeiculos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fotos_veiculo
    {
        public long id_foto { get; set; }
        public string nome { get; set; }
        public long id_veiculo { get; set; }
        public string arquivo { get; set; }
    
        public virtual veiculos veiculos { get; set; }
    }
}
