//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectVeiculos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VeiculosDBEntities : DbContext
    {
        public VeiculosDBEntities()
            : base("name=VeiculosDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fotos_veiculo> fotos_veiculo { get; set; }
        public virtual DbSet<tipos_veiculo> tipos_veiculo { get; set; }
        public virtual DbSet<veiculos> veiculos { get; set; }
    }
}
