//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectVeiculos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipos_veiculo
    {
        public tipos_veiculo()
        {
            this.veiculos = new HashSet<veiculos>();
        }
    
        public long id_tipo_veiculo { get; set; }
        public string nome { get; set; }
    
        public virtual ICollection<veiculos> veiculos { get; set; }
    }
}
